spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/werewolf_vampire_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  sql:
    init:
      mode: always
      
logging:
  level:
    com.werewolfvampire.game: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE