server:
  port: 8080

spring:
  application:
    name: werewolf-vampire-game
  profiles:
    active: dev

jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000  # 24 horas em millisegundos

logging:
  level:
    com.werewolfvampire.game: DEBUG
    org.springframework.security: DEBUG